@startuml

title __PROYECTO_FINAL_LDH's Class Diagram__\n

  namespace recommendation_system {
    class recommendation_system.AllFilters {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.DirectorsFilter {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.EfficientRater {
    }
  }
  

  namespace recommendation_system {
    interface recommendation_system.Filter {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.FirstRatings {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.FourthRatings {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.FourthRatingsOptimizedByWeiXu {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.GenreFilter {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.MinutesFilter {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.Movie {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.MovieDatabase {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.MovieRunnerAverage {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.MovieRunnerSimilarRatings {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.MovieRunnerSimilarRatingsOptimizedByWeiXu {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.MovieRunnerWithFilters {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.PlainRater {
    }
  }
  

  namespace recommendation_system {
    interface recommendation_system.Rater {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.RaterDatabase {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.Rating {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.RecommendationRunner {
    }
  }
  

  namespace recommendation_system {
    interface recommendation_system.Recommender {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.SecondRatings {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.ThirdRatings {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.TrueFilter {
    }
  }
  

  namespace recommendation_system {
    class recommendation_system.YearAfterFilter {
    }
  }
  

  recommendation_system.AllFilters .up.|> recommendation_system.Filter
  recommendation_system.DirectorsFilter .up.|> recommendation_system.Filter
  recommendation_system.EfficientRater .up.|> recommendation_system.Rater
  recommendation_system.GenreFilter .up.|> recommendation_system.Filter
  recommendation_system.MinutesFilter .up.|> recommendation_system.Filter
  recommendation_system.PlainRater .up.|> recommendation_system.Rater
  recommendation_system.Rating .up.|> java.lang.Comparable
  recommendation_system.RecommendationRunner .up.|> recommendation_system.Recommender
  recommendation_system.TrueFilter .up.|> recommendation_system.Filter
  recommendation_system.YearAfterFilter .up.|> recommendation_system.Filter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
