version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports


workflows:
  maven_test:
    jobs:
      - build-and-test
